services:
  database:
    image: 'postgres:15.2'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_USER=excelUser'
      - 'POSTGRES_DB=excel'
      - 'POSTGRES_PASSWORD=secret'
    #volumes:
    #  - ./postgres:/docker-entrypoint-initdb.d/