server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: update
upload:
  baseUrl: http://202.205.188.198:9000
  clientId: 3636000538
  username: jxsyyxxfoin
  password: mhxdivsv2t
  appKey: nUwdjZrD