# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  HOSTNAME: 192.168.2.104
  MODULE: jx530-excel-importer

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.7.0
      with:
        node-version: 16
    - name: Build Frontend
      run: npm install && npm run build
      working-directory: 'frontend'
    - name: Copy Build File
      run: mkdir -p src/main/resources/static/ && cp -R frontend/build/* src/main/resources/static/
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Dockerhub Registry
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_REGISTRY_USERNAME}}
        password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: holmofy/${{env.MODULE}}:latest

    - name: Install ssh-key
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ secrets.ID_RSA }}
        ssh-host: ${{env.HOSTNAME}}
    - name: Deploy Server
      run: |
        echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -t rsa $HOSTNAME >> ~/.ssh/known_hosts
        scp -i ~/.ssh/id_rsa -r ./docker-compose.yaml root@$HOSTNAME:docker-compose.yaml
        ssh -i ~/.ssh/id_rsa root@$HOSTNAME "docker pull holmofy/$MODULE:latest;docker-compose up -d $MODULE"
